# This is a basic workflow to help you get started with Actions

name: Weird w*rkflow shit

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make pinggy folder
        run: |
         net user atmin M@hm3n44794 /add
         net localgroup "Remote Desktop Users" atmin /add
      # Runs a single command using the runners shell
      - name: Fetch pinggy
        run: powershell -Command "Invoke-WebRequest -Uri 'https://github.com/Pinggy-io/cli-js/releases/download/v0.4.6/pinggy-win-x64.exe' -OutFile 'D:\pinggy.exe
      - name: Enable RDP Server
        run: |
          reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
      # Run another command
      - name: Start pinggy
        run: D:\pinggy.exe  -p 443 -R0:127.0.0.1:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 a1L5zumteww+tcp@free.pinggy.io
        
